// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _my_wheaterImpl_h_
#define _my_wheaterImpl_h_

#include "my_wheater.h"


  //! implementation of my_wheater service
  class my_wheaterImpl: public my_wheater
  {
  public:
    my_wheaterImpl();
    virtual ~my_wheaterImpl();
    virtual void OnCreate();
    virtual void OnDestroy();
    virtual int WHcreate();
    virtual int WHinit();
    virtual int WHsync(int t0, int t1, double heating_element_capacity, double temperature, double tank_setpoint, double tank_UA, double water_demand, double tank_volume, double thermostat_deadband);
    virtual int WHcommit();
    virtual int WHtank_state();
    virtual int WHpostsync();
    virtual void WHset_time_to_transition();
    virtual int WHset_current_model_and_load_state();
    virtual double WHdhdt(double h);
    virtual double WHactual_kW();
    virtual double WHnew_time_1node(double T0, double T1);
    virtual double WHnew_temp_1node(double T0, double delta_t);
    virtual double WHnew_time_2zone(double h0, double h1);
    virtual double WHnew_h_2zone(double h0, double delta_t);
    virtual double WHget_Tambient();
  };


#endif // _my_wheaterImpl_h_
