// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _MY_WHEATER_H_
#define _MY_WHEATER_H_

#include <staff/common/IService.h>


  //! my_wheater service
  class my_wheater: public staff::IService
  {
  public:
    // add your opperations here. Example:
    // virtual void MyOperation() = 0;
virtual int WHcreate() = 0;
virtual int WHinit() = 0;
virtual int WHsync(int t0, int t1, double heating_element_capacity, double temperature, double tank_setpoint, double tank_UA, double water_demand, double tank_volume, double thermostat_deadband) = 0;
virtual int WHcommit() = 0;
virtual int WHtank_state() = 0;
virtual int WHpostsync() = 0;
virtual void WHset_time_to_transition() = 0;
virtual int WHset_current_model_and_load_state() = 0;
virtual double WHdhdt(double h) = 0;
virtual double WHactual_kW() = 0;
virtual  double WHnew_time_1node(double T0, double T1) = 0;
virtual  double WHnew_temp_1node(double T0, double delta_t) = 0;
virtual double WHnew_time_2zone(double h0, double h1) = 0;
virtual  double WHnew_h_2zone(double h0, double delta_t) = 0;
virtual double WHget_Tambient() = 0;

  };


#endif // _MY_WHEATER_H_

