// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _my_microturbine_h_
#define _my_microturbine_h_

#include <staff/common/IService.h>

// *interface.targetNamespace: http://tempui.org/
// *interface.url: http://10.96.12.45:9090/axis2/services/staff.wsdl.Wsdl/get/my_microturbine/my_microturbine.wsdl



  //! my_microturbine service
  // *serviceUri: http://10.96.12.45:9090/axis2/services/my_microturbine
  // *soapVersion: 1.1
  // *targetNamespace: http://tempui.org/
  class my_microturbine: public staff::IService
  {
  public:
    // *requestElement: microturbine_init
    // *responseElement: microturbine_initResult
    virtual double microturbine_init() = 0;

    // *requestElement: microturbine_presync
    // *responseElement: microturbine_presyncResult
    virtual int microturbine_presync(int t0, int t1) = 0;

    // *requestElement: microturbine_sync
    // *responseElement: microturbine_syncResult
    virtual double microturbine_sync(double CircuitA_V_Out_re, double CircuitA_V_Out_im, double CircuitB_V_Out_re, double CircuitB_V_Out_im, double CircuitC_V_Out_re, double CircuitC_V_Out_im, double LineA_V_Out_re, double LineA_V_Out_im, double LineB_V_Out_re, double LineB_V_Out_im, double LineC_V_Out_re, double LineC_V_Out_im) = 0;
  };


#endif // _my_microturbine_h_

