// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _my_solarProxy_h_
#define _my_solarProxy_h_

#include <staff/client/ServiceClient.h>
#include "my_solar.h"


//! Proxy for component service my_solar
class my_solarProxy: public my_solar
{
public:
  my_solarProxy();
  virtual ~my_solarProxy();
  void Init(const std::string& sServiceUri, const std::string& sSessionId, const std::string& sInstanceId);
  void Deinit();
  virtual staff::ServiceClient* GetClient();
  double solarcreate();
  int solarinit(int gen_mode_v, int gen_status_v, int panel_type_v);
  double solarsync(int t0, int t1);
private:
  mutable staff::ServiceClient m_tClient;
  std::string m_sServiceUri;
};


namespace staff
{
  class DataObject;
}

#endif

