// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _my_wind_turbine_h_
#define _my_wind_turbine_h_

#include <staff/common/IService.h>

// *interface.targetNamespace: http://tempui.org/
// *interface.url: http://10.96.12.45:9090/axis2/services/staff.wsdl.Wsdl/get/my_wind_turbine/my_wind_turbine.wsdl



  //! my_wind_turbine service
  // *serviceUri: http://10.96.12.45:9090/axis2/services/my_wind_turbine
  // *soapVersion: 1.1
  // *targetNamespace: http://tempui.org/
  class my_wind_turbine: public staff::IService
  {
  public:
    // *requestElement: windturb_dgcreate
    // *responseElement: windturb_dgcreateResult
    virtual double windturb_dgcreate() = 0;

    // *requestElement: windturb_dginit
    // *responseElement: windturb_dginitResult
    virtual int windturb_dginit(double pLine_I_A_Re, double pLine_I_A_Im, double pLine_I_B_Re, double pLine_I_B_Im, double pLine_I_C_Re, double pLine_I_C_Im) = 0;

    // *requestElement: windturb_dgsync
    // *responseElement: windturb_dgsyncResult
    virtual double windturb_dgsync(double pCircuit_V_A_Re, double pCircuit_V_A_Im, double pCircuit_V_B_Re, double pCircuit_V_B_Im, double pCircuit_V_C_Re, double pCircuit_V_C_Im) = 0;

    // *requestElement: windturb_dg_postsync
    // *responseElement: windturb_dg_postsyncResult
    virtual int windturb_dg_postsync(int t0, int t1) = 0;
  };


#endif // _my_wind_turbine_h_

