// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _MY_WIND_TURBINE_H_
#define _MY_WIND_TURBINE_H_

#include <staff/common/IService.h>


  //! my_wind_turbine service
  class my_wind_turbine: public staff::IService
  {
  public:
    // add your opperations here. Example:
    // virtual void MyOperation() = 0;
	virtual double windturb_dgcreate() = 0;
	virtual int windturb_dginit(double pLine_I_A_Re, double pLine_I_A_Im,double pLine_I_B_Re, double pLine_I_B_Im,double pLine_I_C_Re, double pLine_I_C_Im) = 0;
	virtual double windturb_dgsync(double pCircuit_V_A_Re, double pCircuit_V_A_Im,double pCircuit_V_B_Re, double pCircuit_V_B_Im,double pCircuit_V_C_Re, double pCircuit_V_C_Im) = 0;
	virtual int windturb_dg_postsync(int t0, int t1) = 0;

  };


#endif // _MY_WIND_TURBINE_H_

