// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _my_wind_turbineImpl_h_
#define _my_wind_turbineImpl_h_

#include "my_wind_turbine.h"


  //! implementation of my_wind_turbine service
  class my_wind_turbineImpl: public my_wind_turbine
  {
  public:
    my_wind_turbineImpl();
    virtual ~my_wind_turbineImpl();
    virtual void OnCreate();
    virtual void OnDestroy();
    virtual double windturb_dgcreate();
    virtual int windturb_dginit(double pLine_I_A_Re, double pLine_I_A_Im, double pLine_I_B_Re, double pLine_I_B_Im, double pLine_I_C_Re, double pLine_I_C_Im);
    virtual double windturb_dgsync(double pCircuit_V_A_Re, double pCircuit_V_A_Im, double pCircuit_V_B_Re, double pCircuit_V_B_Im, double pCircuit_V_C_Re, double pCircuit_V_C_Im);
    virtual int windturb_dg_postsync(int t0, int t1);
  };


#endif // _my_wind_turbineImpl_h_
