// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _MY_SOLAR_H_
#define _MY_SOLAR_H_

#include <staff/common/IService.h>


  //! my_solar service
  class my_solar: public staff::IService
  {
  public:
    // add your opperations here. Example:
    // virtual void MyOperation() = 0;
	virtual double solarcreate() = 0;
	virtual int solarinit(int gen_mode_v, int gen_status_v, int panel_type_v) = 0;
	virtual double solarsync(int t0, int t1) = 0;

  };


#endif // _MY_SOLAR_H_

