// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _MY_CONTROLLER_H_
#define _MY_CONTROLLER_H_

#include <staff/common/IService.h>


  //! my_controller service
  class my_controller: public staff::IService
  {
  public:
    // add your opperations here. Example:
    // virtual void MyOperation() = 0;
	virtual int COinit(double market_init_price, int pstate, int market_period, int control_mode, double psetpoint, double base_setpoint, double heating_base_setpoint, double cooling_base_setpoint) = 0;
	virtual int COpresync(double base_setpoint, double psetpoint, int control_mode) = 0;
	virtual double COsync(double load, double demand, int pstate, double total, double target, double pAvg, double pStd, double base_setpoint, int control_mode, double market_current_frameclearing_price) = 0;
	virtual double COpostsync(int control_mode, double base_setpoint) = 0;
 };


#endif // _MY_CONTROLLER_H_

