// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _my_controllerImpl_h_
#define _my_controllerImpl_h_

#include "my_controller.h"


  //! implementation of my_controller service
  class my_controllerImpl: public my_controller
  {
  public:
    my_controllerImpl();
    virtual ~my_controllerImpl();
    virtual void OnCreate();
    virtual void OnDestroy();
    virtual int COinit(double market_init_price, int pstate, int market_period, int control_mode, double psetpoint, double base_setpoint, double heating_base_setpoint, double cooling_base_setpoint);
    virtual int COpresync(double base_setpoint, double psetpoint, int control_mode);
    virtual double COsync(double load, double demand, int pstate, double total, double target, double pAvg, double pStd, double base_setpoint, int control_mode, double market_current_frameclearing_price);
    virtual double COpostsync(int control_mode, double base_setpoint);
  };


#endif // _my_controllerImpl_h_
