// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#include <staff/utils/PluginExport.h>
#include <staff/utils/SharedPtr.h>
#include "my_microturbineWrapper.h"
#include "ComponentImpl.h"

STAFF_DECLARE_PLUGIN(::ComponentImpl)


  ComponentImpl::ComponentImpl()
  {
    RegisterService("my_microturbine", new ::my_microturbineWrapper(this));
  }

  ComponentImpl::~ComponentImpl()
  {
  }

  const std::string& ComponentImpl::GetName() const
  {
    return m_sName;
  }

  const std::string ComponentImpl::m_sName = "";



