// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _my_microturbineImpl_h_
#define _my_microturbineImpl_h_

#include "my_microturbine.h"


  //! implementation of my_microturbine service
  class my_microturbineImpl: public my_microturbine
  {
  public:
    my_microturbineImpl();
    virtual ~my_microturbineImpl();
    virtual void OnCreate();
    virtual void OnDestroy();
    virtual double microturbine_init();
    virtual int microturbine_presync(int t0, int t1);
    virtual double microturbine_sync(double CircuitA_V_Out_re, double CircuitA_V_Out_im, double CircuitB_V_Out_re, double CircuitB_V_Out_im, double CircuitC_V_Out_re, double CircuitC_V_Out_im, double LineA_V_Out_re, double LineA_V_Out_im, double LineB_V_Out_re, double LineB_V_Out_im, double LineC_V_Out_re, double LineC_V_Out_im);
  };


#endif // _my_microturbineImpl_h_
